### ISSUE TITLE
Redundant keys in the state_dict

### ISSUE THREAD

**Issue by haohaoqian** [yuzhimanhua/SciMult#1]
I find your design of multi-task contrastive learning pre-training interesting, and the models seem useful in embedding scientific documents for various downstream tasks. 
Thereby, I want to test it on my work, but encounter a small problem in loading the checkpoints.

Specifically, when loading the checkpoints (I tried _vanilla and _moe) with `biencoder.load_state_dict(state_dict['model_dict'])`, there are two redundant keys in the state_dict, saying `question_model.encoder.embeddings.position_ids` and `ctx_model.encoder.embeddings.position_ids`, that do not match the config of model structure and hinder the loading.

It seems that they are not part of the model parameters, and I simply use
`del state_dict['model_dict']["question_model.encoder.embeddings.position_ids"]`
`del state_dict['model_dict']["ctx_model.encoder.embeddings.position_ids"]`
before `biencoder.load_state_dict(state_dict['model_dict'])`.
Then, I can successfully load the checkpoints and get the embeddings (which actually work well on my testing).

Hopefully you can check this!

**Comment by yuzhimanhua** [comment]
Thank you very much for your careful review and detailed notes! We will revise our code accordingly.

**Comment by haohaoqian** [comment]
Thanks. We will appreciate it so much.
